#pragma once
// Koffing sprite library — pollution level in, pixels out.
//
// Usage:
//   #include "koffing_gfx.h"
//   koffing_draw(display, 7, 0, 0);  // level 0-10
//
// Draws a 64x64 scene (body + clouds) at the given origin.
// Works with any Adafruit_GFX-derived display (SSD1306, ST7735, etc).

#include <Adafruit_GFX.h>
#include <stdint.h>

#define KOFFING_LEVEL_MAX 10

// --- Mono bitmap data (PROGMEM) ---
// Generated by art/generate.py — do not edit by hand.

#include "koffing_happy_mono.h"
#include "koffing_grin_mono.h"
#include "koffing_thrilled_mono.h"
#include "koffing_ecstatic_mono.h"
#include "cloud_small_mono.h"
#include "cloud_medium_mono.h"
#include "cloud_large_mono.h"

// --- Internal: cloud placement pool ---
// 10 positions. Small wisps interleaved between larger clouds.
// Each: {sprite_type (0=small, 1=medium, 2=large), x, y} in 64x64 scene space.

typedef struct {
    uint8_t type;
    int8_t x;
    int8_t y;
} _KoffingCloud;

static const _KoffingCloud _cloud_pool[] PROGMEM = {
    {0, 48, 12},   //  1: wisp, right
    {0, 26,  0},   //  2: wisp, top-center
    {1,  0,  2},   //  3: puff, upper-left
    {0,  0, 26},   //  4: wisp, left
    {1, 42, 42},   //  5: puff, lower-right
    {0, 26, 52},   //  6: wisp, bottom-center
    {2,  0, 40},   //  7: billow, lower-left
    {0, 52, 28},   //  8: wisp, far-right
    {2, 40,  0},   //  9: billow, upper-right
    {0, 50, 50},   // 10: wisp, far lower-right
};

static const uint8_t* const _cloud_bitmaps[] = {
    cloud_small_mono, cloud_medium_mono, cloud_large_mono,
};
static const uint8_t _cloud_widths[] = {
    CLOUD_SMALL_WIDTH, CLOUD_MEDIUM_WIDTH, CLOUD_LARGE_WIDTH,
};
static const uint8_t _cloud_heights[] = {
    CLOUD_SMALL_HEIGHT, CLOUD_MEDIUM_HEIGHT, CLOUD_LARGE_HEIGHT,
};

// --- Internal: face selection ---
// level 0     → happy
// level 1-4   → grin
// level 5-6   → thrilled
// level 7-10  → ecstatic

static inline const uint8_t* _koffing_face(uint8_t level) {
    if (level == 0) return koffing_happy_mono;
    if (level <= 4) return koffing_grin_mono;
    if (level <= 6) return koffing_thrilled_mono;
    return koffing_ecstatic_mono;
}

// --- Public API ---

// Draw a 64x64 Koffing scene at (ox, oy).
// level: 0 (clean air, happy, no clouds) to 10 (hazardous, ecstatic, surrounded).
// color: pixel color (WHITE for mono OLED, any RGB565 for color).
static inline void koffing_draw(Adafruit_GFX &gfx, uint8_t level, int16_t ox, int16_t oy, uint16_t color = 1) {
    if (level > KOFFING_LEVEL_MAX) level = KOFFING_LEVEL_MAX;

    // Draw clouds (level N = N clouds from the pool)
    for (uint8_t i = 0; i < level; i++) {
        _KoffingCloud c;
        memcpy_P(&c, &_cloud_pool[i], sizeof(c));
        gfx.drawXBitmap(
            ox + c.x, oy + c.y,
            _cloud_bitmaps[c.type],
            _cloud_widths[c.type], _cloud_heights[c.type],
            color
        );
    }

    // Draw body centered in 64x64 scene
    gfx.drawXBitmap(ox + 16, oy + 16, _koffing_face(level), 32, 32, color);
}
